ClusterName=hpc-poc
SlurmctldHost=slurmctld

MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=2

SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld

SwitchType=switch/none
TaskPlugin=task/none

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

AccountingStorageType=accounting_storage/none
JobAcctGatherType=jobacct_gather/none

SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldDebug=info
SlurmdDebug=info

NodeName=node1 CPUs=2 RealMemory=512 State=UNKNOWN
NodeName=node2 CPUs=2 RealMemory=512 State=UNKNOWN

PartitionName=compute Nodes=node[1-2] Default=YES MaxTime=01:00:00 State=UP
